export interface CityEntry {
  label: string
  flag: string
  iana: string
  search?: string
}

export const ALL_SEARCHABLE_CITIES: CityEntry[] = [
  // ── United States ─────────────────────────────────────────────────────────
  // Pacific
  { label: 'Los Angeles', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa united states la pacific' },
  { label: 'San Francisco', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa sf bay area pacific' },
  { label: 'San Jose', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa silicon valley pacific' },
  { label: 'San Diego', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Sacramento', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa capital pacific' },
  { label: 'Oakland', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa bay area pacific' },
  { label: 'Long Beach', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Fresno', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Bakersfield', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Riverside', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Santa Ana', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific orange county' },
  { label: 'Anaheim', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific orange county disneyland' },
  { label: 'Irvine', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Santa Barbara', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'california ca usa pacific' },
  { label: 'Reno', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'nevada nv usa pacific' },
  { label: 'Las Vegas', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'nevada nv usa pacific' },
  { label: 'Seattle', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'washington wa usa pacific' },
  { label: 'Tacoma', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'washington wa usa pacific' },
  { label: 'Spokane', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'washington wa usa pacific' },
  { label: 'Portland', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'oregon or usa pacific' },
  { label: 'Eugene', flag: '🇺🇸', iana: 'America/Los_Angeles', search: 'oregon or usa pacific' },
  // Mountain
  { label: 'Phoenix', flag: '🇺🇸', iana: 'America/Phoenix', search: 'arizona az usa mountain' },
  { label: 'Tucson', flag: '🇺🇸', iana: 'America/Phoenix', search: 'arizona az usa mountain' },
  { label: 'Mesa', flag: '🇺🇸', iana: 'America/Phoenix', search: 'arizona az usa mountain' },
  { label: 'Scottsdale', flag: '🇺🇸', iana: 'America/Phoenix', search: 'arizona az usa mountain' },
  { label: 'Denver', flag: '🇺🇸', iana: 'America/Denver', search: 'colorado co usa mountain' },
  { label: 'Colorado Springs', flag: '🇺🇸', iana: 'America/Denver', search: 'colorado co usa mountain' },
  { label: 'Aurora', flag: '🇺🇸', iana: 'America/Denver', search: 'colorado co usa mountain' },
  { label: 'Fort Collins', flag: '🇺🇸', iana: 'America/Denver', search: 'colorado co usa mountain' },
  { label: 'Boulder', flag: '🇺🇸', iana: 'America/Denver', search: 'colorado co usa mountain' },
  { label: 'Salt Lake City', flag: '🇺🇸', iana: 'America/Denver', search: 'utah ut usa mountain slc' },
  { label: 'Albuquerque', flag: '🇺🇸', iana: 'America/Denver', search: 'new mexico nm usa mountain' },
  { label: 'Santa Fe', flag: '🇺🇸', iana: 'America/Denver', search: 'new mexico nm usa mountain capital' },
  { label: 'Boise', flag: '🇺🇸', iana: 'America/Boise', search: 'idaho id usa mountain capital' },
  { label: 'Billings', flag: '🇺🇸', iana: 'America/Denver', search: 'montana mt usa mountain' },
  { label: 'Cheyenne', flag: '🇺🇸', iana: 'America/Denver', search: 'wyoming wy usa mountain capital' },
  // Central
  { label: 'Chicago', flag: '🇺🇸', iana: 'America/Chicago', search: 'illinois il usa central midwest' },
  { label: 'Dallas', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa central' },
  { label: 'Fort Worth', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa central dfw' },
  { label: 'Houston', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa central' },
  { label: 'San Antonio', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa central' },
  { label: 'Austin', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa central capital' },
  { label: 'El Paso', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa mountain border' },
  { label: 'Lubbock', flag: '🇺🇸', iana: 'America/Chicago', search: 'texas tx usa central' },
  { label: 'Minneapolis', flag: '🇺🇸', iana: 'America/Chicago', search: 'minnesota mn usa central midwest' },
  { label: 'St. Paul', flag: '🇺🇸', iana: 'America/Chicago', search: 'minnesota mn usa central capital' },
  { label: 'Kansas City', flag: '🇺🇸', iana: 'America/Chicago', search: 'missouri mo kansas ks usa central' },
  { label: 'St. Louis', flag: '🇺🇸', iana: 'America/Chicago', search: 'missouri mo usa central midwest' },
  { label: 'New Orleans', flag: '🇺🇸', iana: 'America/Chicago', search: 'louisiana la usa central nola' },
  { label: 'Baton Rouge', flag: '🇺🇸', iana: 'America/Chicago', search: 'louisiana la usa central capital' },
  { label: 'Nashville', flag: '🇺🇸', iana: 'America/Chicago', search: 'tennessee tn usa central capital' },
  { label: 'Memphis', flag: '🇺🇸', iana: 'America/Chicago', search: 'tennessee tn usa central' },
  { label: 'Milwaukee', flag: '🇺🇸', iana: 'America/Chicago', search: 'wisconsin wi usa central' },
  { label: 'Madison', flag: '🇺🇸', iana: 'America/Chicago', search: 'wisconsin wi usa central capital' },
  { label: 'Oklahoma City', flag: '🇺🇸', iana: 'America/Chicago', search: 'oklahoma ok usa central capital' },
  { label: 'Tulsa', flag: '🇺🇸', iana: 'America/Chicago', search: 'oklahoma ok usa central' },
  { label: 'Omaha', flag: '🇺🇸', iana: 'America/Chicago', search: 'nebraska ne usa central' },
  { label: 'Lincoln', flag: '🇺🇸', iana: 'America/Chicago', search: 'nebraska ne usa central capital' },
  { label: 'Des Moines', flag: '🇺🇸', iana: 'America/Chicago', search: 'iowa ia usa central capital' },
  { label: 'Sioux Falls', flag: '🇺🇸', iana: 'America/Chicago', search: 'south dakota sd usa central' },
  { label: 'Fargo', flag: '🇺🇸', iana: 'America/Chicago', search: 'north dakota nd usa central' },
  { label: 'Wichita', flag: '🇺🇸', iana: 'America/Chicago', search: 'kansas ks usa central' },
  { label: 'Little Rock', flag: '🇺🇸', iana: 'America/Chicago', search: 'arkansas ar usa central capital' },
  { label: 'Jackson', flag: '🇺🇸', iana: 'America/Chicago', search: 'mississippi ms usa central capital' },
  { label: 'Birmingham', flag: '🇺🇸', iana: 'America/Chicago', search: 'alabama al usa central' },
  { label: 'Montgomery', flag: '🇺🇸', iana: 'America/Chicago', search: 'alabama al usa central capital' },
  { label: 'Mobile', flag: '🇺🇸', iana: 'America/Chicago', search: 'alabama al usa central' },
  // Eastern
  { label: 'New York', flag: '🇺🇸', iana: 'America/New_York', search: 'new york ny nyc usa eastern' },
  { label: 'Miami', flag: '🇺🇸', iana: 'America/New_York', search: 'florida fl usa eastern' },
  { label: 'Orlando', flag: '🇺🇸', iana: 'America/New_York', search: 'florida fl usa eastern' },
  { label: 'Tampa', flag: '🇺🇸', iana: 'America/New_York', search: 'florida fl usa eastern' },
  { label: 'Fort Lauderdale', flag: '🇺🇸', iana: 'America/New_York', search: 'florida fl usa eastern' },
  { label: 'Jacksonville', flag: '🇺🇸', iana: 'America/New_York', search: 'florida fl usa eastern' },
  { label: 'Tallahassee', flag: '🇺🇸', iana: 'America/New_York', search: 'florida fl usa eastern capital' },
  { label: 'Atlanta', flag: '🇺🇸', iana: 'America/New_York', search: 'georgia ga usa eastern capital' },
  { label: 'Savannah', flag: '🇺🇸', iana: 'America/New_York', search: 'georgia ga usa eastern' },
  { label: 'Boston', flag: '🇺🇸', iana: 'America/New_York', search: 'massachusetts ma usa eastern capital' },
  { label: 'Worcester', flag: '🇺🇸', iana: 'America/New_York', search: 'massachusetts ma usa eastern' },
  { label: 'Washington DC', flag: '🇺🇸', iana: 'America/New_York', search: 'district columbia dc usa eastern capital federal' },
  { label: 'Philadelphia', flag: '🇺🇸', iana: 'America/New_York', search: 'pennsylvania pa usa eastern philly' },
  { label: 'Pittsburgh', flag: '🇺🇸', iana: 'America/New_York', search: 'pennsylvania pa usa eastern' },
  { label: 'Baltimore', flag: '🇺🇸', iana: 'America/New_York', search: 'maryland md usa eastern' },
  { label: 'Charlotte', flag: '🇺🇸', iana: 'America/New_York', search: 'north carolina nc usa eastern' },
  { label: 'Raleigh', flag: '🇺🇸', iana: 'America/New_York', search: 'north carolina nc usa eastern capital' },
  { label: 'Greensboro', flag: '🇺🇸', iana: 'America/New_York', search: 'north carolina nc usa eastern' },
  { label: 'Durham', flag: '🇺🇸', iana: 'America/New_York', search: 'north carolina nc usa eastern research triangle' },
  { label: 'Columbia', flag: '🇺🇸', iana: 'America/New_York', search: 'south carolina sc usa eastern capital' },
  { label: 'Charleston', flag: '🇺🇸', iana: 'America/New_York', search: 'south carolina sc usa eastern' },
  { label: 'Richmond', flag: '🇺🇸', iana: 'America/New_York', search: 'virginia va usa eastern capital' },
  { label: 'Virginia Beach', flag: '🇺🇸', iana: 'America/New_York', search: 'virginia va usa eastern' },
  { label: 'Norfolk', flag: '🇺🇸', iana: 'America/New_York', search: 'virginia va usa eastern' },
  { label: 'Detroit', flag: '🇺🇸', iana: 'America/Detroit', search: 'michigan mi usa eastern' },
  { label: 'Grand Rapids', flag: '🇺🇸', iana: 'America/Detroit', search: 'michigan mi usa eastern' },
  { label: 'Cleveland', flag: '🇺🇸', iana: 'America/New_York', search: 'ohio oh usa eastern' },
  { label: 'Columbus', flag: '🇺🇸', iana: 'America/New_York', search: 'ohio oh usa eastern capital' },
  { label: 'Cincinnati', flag: '🇺🇸', iana: 'America/New_York', search: 'ohio oh usa eastern' },
  { label: 'Indianapolis', flag: '🇺🇸', iana: 'America/Indiana/Indianapolis', search: 'indiana in usa eastern capital' },
  { label: 'Louisville', flag: '🇺🇸', iana: 'America/Kentucky/Louisville', search: 'kentucky ky usa eastern' },
  { label: 'Lexington', flag: '🇺🇸', iana: 'America/New_York', search: 'kentucky ky usa eastern' },
  { label: 'Knoxville', flag: '🇺🇸', iana: 'America/New_York', search: 'tennessee tn usa eastern' },
  { label: 'Chattanooga', flag: '🇺🇸', iana: 'America/New_York', search: 'tennessee tn usa eastern' },
  { label: 'Buffalo', flag: '🇺🇸', iana: 'America/New_York', search: 'new york ny usa eastern' },
  { label: 'Rochester', flag: '🇺🇸', iana: 'America/New_York', search: 'new york ny usa eastern' },
  { label: 'Albany', flag: '🇺🇸', iana: 'America/New_York', search: 'new york ny usa eastern capital' },
  { label: 'Syracuse', flag: '🇺🇸', iana: 'America/New_York', search: 'new york ny usa eastern' },
  { label: 'Newark', flag: '🇺🇸', iana: 'America/New_York', search: 'new jersey nj usa eastern' },
  { label: 'Jersey City', flag: '🇺🇸', iana: 'America/New_York', search: 'new jersey nj usa eastern' },
  { label: 'Trenton', flag: '🇺🇸', iana: 'America/New_York', search: 'new jersey nj usa eastern capital' },
  { label: 'Providence', flag: '🇺🇸', iana: 'America/New_York', search: 'rhode island ri usa eastern capital' },
  { label: 'Hartford', flag: '🇺🇸', iana: 'America/New_York', search: 'connecticut ct usa eastern capital' },
  { label: 'New Haven', flag: '🇺🇸', iana: 'America/New_York', search: 'connecticut ct usa eastern yale' },
  { label: 'Bridgeport', flag: '🇺🇸', iana: 'America/New_York', search: 'connecticut ct usa eastern' },
  { label: 'Manchester', flag: '🇺🇸', iana: 'America/New_York', search: 'new hampshire nh usa eastern' },
  { label: 'Portland ME', flag: '🇺🇸', iana: 'America/New_York', search: 'maine me usa eastern' },
  { label: 'Burlington VT', flag: '🇺🇸', iana: 'America/New_York', search: 'vermont vt usa eastern' },
  { label: 'Wilmington', flag: '🇺🇸', iana: 'America/New_York', search: 'delaware de usa eastern' },
  // Special
  { label: 'Honolulu', flag: '🇺🇸', iana: 'Pacific/Honolulu', search: 'hawaii hi usa pacific' },
  { label: 'Maui', flag: '🇺🇸', iana: 'Pacific/Honolulu', search: 'hawaii hi usa pacific' },
  { label: 'Anchorage', flag: '🇺🇸', iana: 'America/Anchorage', search: 'alaska ak usa' },
  { label: 'Fairbanks', flag: '🇺🇸', iana: 'America/Anchorage', search: 'alaska ak usa' },
  { label: 'Juneau', flag: '🇺🇸', iana: 'America/Juneau', search: 'alaska ak usa capital' },

  // ── Canada ────────────────────────────────────────────────────────────────
  { label: 'Toronto', flag: '🇨🇦', iana: 'America/Toronto', search: 'ontario canada eastern' },
  { label: 'Ottawa', flag: '🇨🇦', iana: 'America/Toronto', search: 'ontario canada eastern capital' },
  { label: 'Hamilton', flag: '🇨🇦', iana: 'America/Toronto', search: 'ontario canada eastern' },
  { label: 'London ON', flag: '🇨🇦', iana: 'America/Toronto', search: 'ontario canada eastern' },
  { label: 'Mississauga', flag: '🇨🇦', iana: 'America/Toronto', search: 'ontario canada eastern' },
  { label: 'Montreal', flag: '🇨🇦', iana: 'America/Toronto', search: 'quebec canada eastern' },
  { label: 'Quebec City', flag: '🇨🇦', iana: 'America/Toronto', search: 'quebec canada eastern capital' },
  { label: 'Vancouver', flag: '🇨🇦', iana: 'America/Vancouver', search: 'british columbia bc canada pacific' },
  { label: 'Victoria', flag: '🇨🇦', iana: 'America/Vancouver', search: 'british columbia bc canada pacific capital' },
  { label: 'Calgary', flag: '🇨🇦', iana: 'America/Edmonton', search: 'alberta canada mountain' },
  { label: 'Edmonton', flag: '🇨🇦', iana: 'America/Edmonton', search: 'alberta canada mountain capital' },
  { label: 'Winnipeg', flag: '🇨🇦', iana: 'America/Winnipeg', search: 'manitoba canada central capital' },
  { label: 'Halifax', flag: '🇨🇦', iana: 'America/Halifax', search: 'nova scotia canada atlantic capital' },
  { label: 'Moncton', flag: '🇨🇦', iana: 'America/Moncton', search: 'new brunswick canada atlantic' },
  { label: 'St. Johns NL', flag: '🇨🇦', iana: 'America/St_Johns', search: 'newfoundland canada atlantic capital' },
  { label: 'Saskatoon', flag: '🇨🇦', iana: 'America/Regina', search: 'saskatchewan canada central' },
  { label: 'Regina', flag: '🇨🇦', iana: 'America/Regina', search: 'saskatchewan canada central capital' },

  // ── Mexico ────────────────────────────────────────────────────────────────
  { label: 'Mexico City', flag: '🇲🇽', iana: 'America/Mexico_City', search: 'mexico cdmx df central' },
  { label: 'Guadalajara', flag: '🇲🇽', iana: 'America/Mexico_City', search: 'mexico jalisco central' },
  { label: 'Puebla', flag: '🇲🇽', iana: 'America/Mexico_City', search: 'mexico central' },
  { label: 'Monterrey', flag: '🇲🇽', iana: 'America/Monterrey', search: 'mexico nuevo leon central' },
  { label: 'Cancún', flag: '🇲🇽', iana: 'America/Cancun', search: 'mexico quintana roo cancun yucatan' },
  { label: 'Mérida', flag: '🇲🇽', iana: 'America/Merida', search: 'mexico yucatan merida' },
  { label: 'Tijuana', flag: '🇲🇽', iana: 'America/Tijuana', search: 'mexico baja california pacific border' },
  { label: 'Mexicali', flag: '🇲🇽', iana: 'America/Tijuana', search: 'mexico baja california pacific' },
  { label: 'Ciudad Juárez', flag: '🇲🇽', iana: 'America/Ciudad_Juarez', search: 'mexico chihuahua border' },
  { label: 'Acapulco', flag: '🇲🇽', iana: 'America/Mexico_City', search: 'mexico guerrero' },
  { label: 'Cabo San Lucas', flag: '🇲🇽', iana: 'America/Mazatlan', search: 'mexico baja california sur' },
  { label: 'Puerto Vallarta', flag: '🇲🇽', iana: 'America/Mexico_City', search: 'mexico jalisco' },

  // ── Central America ───────────────────────────────────────────────────────
  { label: 'Guatemala City', flag: '🇬🇹', iana: 'America/Guatemala', search: 'guatemala central america' },
  { label: 'San Salvador', flag: '🇸🇻', iana: 'America/El_Salvador', search: 'el salvador central america' },
  { label: 'Tegucigalpa', flag: '🇭🇳', iana: 'America/Tegucigalpa', search: 'honduras central america' },
  { label: 'Managua', flag: '🇳🇮', iana: 'America/Managua', search: 'nicaragua central america' },
  { label: 'San José CR', flag: '🇨🇷', iana: 'America/Costa_Rica', search: 'costa rica central america' },
  { label: 'Panama City', flag: '🇵🇦', iana: 'America/Panama', search: 'panama central america' },
  { label: 'Belmopan', flag: '🇧🇿', iana: 'America/Belize', search: 'belize central america' },

  // ── Caribbean ─────────────────────────────────────────────────────────────
  { label: 'Havana', flag: '🇨🇺', iana: 'America/Havana', search: 'cuba caribbean' },
  { label: 'Santo Domingo', flag: '🇩🇴', iana: 'America/Santo_Domingo', search: 'dominican republic dr caribbean' },
  { label: 'Port-au-Prince', flag: '🇭🇹', iana: 'America/Port-au-Prince', search: 'haiti caribbean' },
  { label: 'San Juan', flag: '🇵🇷', iana: 'America/Puerto_Rico', search: 'puerto rico caribbean usa' },
  { label: 'Nassau', flag: '🇧🇸', iana: 'America/Nassau', search: 'bahamas caribbean' },
  { label: 'Kingston', flag: '🇯🇲', iana: 'America/Jamaica', search: 'jamaica caribbean' },
  { label: 'Bridgetown', flag: '🇧🇧', iana: 'America/Barbados', search: 'barbados caribbean' },
  { label: 'Port of Spain', flag: '🇹🇹', iana: 'America/Port_of_Spain', search: 'trinidad tobago caribbean' },
  { label: 'Willemstad', flag: '🇨🇼', iana: 'America/Curacao', search: 'curacao caribbean netherlands' },
  { label: 'Castries', flag: '🇱🇨', iana: 'America/St_Lucia', search: 'saint lucia caribbean' },

  // ── South America ─────────────────────────────────────────────────────────
  { label: 'Bogotá', flag: '🇨🇴', iana: 'America/Bogota', search: 'colombia capital' },
  { label: 'Medellín', flag: '🇨🇴', iana: 'America/Bogota', search: 'colombia antioquia' },
  { label: 'Cali', flag: '🇨🇴', iana: 'America/Bogota', search: 'colombia valle' },
  { label: 'Barranquilla', flag: '🇨🇴', iana: 'America/Bogota', search: 'colombia caribbean coast' },
  { label: 'Cartagena', flag: '🇨🇴', iana: 'America/Bogota', search: 'colombia caribbean coast' },
  { label: 'São Paulo', flag: '🇧🇷', iana: 'America/Sao_Paulo', search: 'brazil brasil' },
  { label: 'Rio de Janeiro', flag: '🇧🇷', iana: 'America/Sao_Paulo', search: 'brazil brasil rio' },
  { label: 'Brasília', flag: '🇧🇷', iana: 'America/Sao_Paulo', search: 'brazil brasil capital' },
  { label: 'Salvador', flag: '🇧🇷', iana: 'America/Bahia', search: 'brazil brasil bahia' },
  { label: 'Fortaleza', flag: '🇧🇷', iana: 'America/Fortaleza', search: 'brazil brasil ceara' },
  { label: 'Manaus', flag: '🇧🇷', iana: 'America/Manaus', search: 'brazil brasil amazon' },
  { label: 'Belo Horizonte', flag: '🇧🇷', iana: 'America/Sao_Paulo', search: 'brazil brasil minas gerais' },
  { label: 'Curitiba', flag: '🇧🇷', iana: 'America/Sao_Paulo', search: 'brazil brasil parana' },
  { label: 'Porto Alegre', flag: '🇧🇷', iana: 'America/Sao_Paulo', search: 'brazil brasil rio grande do sul' },
  { label: 'Recife', flag: '🇧🇷', iana: 'America/Recife', search: 'brazil brasil pernambuco' },
  { label: 'Buenos Aires', flag: '🇦🇷', iana: 'America/Argentina/Buenos_Aires', search: 'argentina capital' },
  { label: 'Córdoba', flag: '🇦🇷', iana: 'America/Argentina/Cordoba', search: 'argentina' },
  { label: 'Rosario', flag: '🇦🇷', iana: 'America/Argentina/Buenos_Aires', search: 'argentina' },
  { label: 'Mendoza', flag: '🇦🇷', iana: 'America/Argentina/Mendoza', search: 'argentina wine' },
  { label: 'Santiago', flag: '🇨🇱', iana: 'America/Santiago', search: 'chile capital' },
  { label: 'Valparaíso', flag: '🇨🇱', iana: 'America/Santiago', search: 'chile' },
  { label: 'Lima', flag: '🇵🇪', iana: 'America/Lima', search: 'peru capital' },
  { label: 'Cusco', flag: '🇵🇪', iana: 'America/Lima', search: 'peru inca machu picchu' },
  { label: 'Caracas', flag: '🇻🇪', iana: 'America/Caracas', search: 'venezuela capital' },
  { label: 'Maracaibo', flag: '🇻🇪', iana: 'America/Caracas', search: 'venezuela' },
  { label: 'Quito', flag: '🇪🇨', iana: 'America/Guayaquil', search: 'ecuador capital' },
  { label: 'Guayaquil', flag: '🇪🇨', iana: 'America/Guayaquil', search: 'ecuador' },
  { label: 'La Paz', flag: '🇧🇴', iana: 'America/La_Paz', search: 'bolivia capital' },
  { label: 'Santa Cruz BO', flag: '🇧🇴', iana: 'America/La_Paz', search: 'bolivia' },
  { label: 'Montevideo', flag: '🇺🇾', iana: 'America/Montevideo', search: 'uruguay capital' },
  { label: 'Asunción', flag: '🇵🇾', iana: 'America/Asuncion', search: 'paraguay capital' },
  { label: 'Georgetown', flag: '🇬🇾', iana: 'America/Guyana', search: 'guyana capital' },
  { label: 'Paramaribo', flag: '🇸🇷', iana: 'America/Paramaribo', search: 'suriname capital' },

  // ── United Kingdom ────────────────────────────────────────────────────────
  { label: 'London', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom britain' },
  { label: 'Manchester', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom' },
  { label: 'Birmingham', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom' },
  { label: 'Leeds', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom yorkshire' },
  { label: 'Liverpool', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom' },
  { label: 'Newcastle', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom' },
  { label: 'Sheffield', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom' },
  { label: 'Bristol', flag: '🇬🇧', iana: 'Europe/London', search: 'england uk united kingdom' },
  { label: 'Edinburgh', flag: '🇬🇧', iana: 'Europe/London', search: 'scotland uk united kingdom capital' },
  { label: 'Glasgow', flag: '🇬🇧', iana: 'Europe/London', search: 'scotland uk united kingdom' },
  { label: 'Aberdeen', flag: '🇬🇧', iana: 'Europe/London', search: 'scotland uk united kingdom' },
  { label: 'Cardiff', flag: '🇬🇧', iana: 'Europe/London', search: 'wales uk united kingdom capital' },
  { label: 'Belfast', flag: '🇬🇧', iana: 'Europe/London', search: 'northern ireland uk united kingdom capital' },
  { label: 'Dublin', flag: '🇮🇪', iana: 'Europe/Dublin', search: 'ireland eire capital' },
  { label: 'Cork', flag: '🇮🇪', iana: 'Europe/Dublin', search: 'ireland' },

  // ── France ────────────────────────────────────────────────────────────────
  { label: 'Paris', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french capital' },
  { label: 'Lyon', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french' },
  { label: 'Marseille', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french' },
  { label: 'Toulouse', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french' },
  { label: 'Nice', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french riviera cote azur' },
  { label: 'Nantes', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french' },
  { label: 'Bordeaux', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french wine' },
  { label: 'Strasbourg', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french alsace' },
  { label: 'Lille', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french' },
  { label: 'Montpellier', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french' },
  { label: 'Cannes', flag: '🇫🇷', iana: 'Europe/Paris', search: 'france french film festival riviera' },

  // ── Germany ───────────────────────────────────────────────────────────────
  { label: 'Berlin', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland capital' },
  { label: 'Munich', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland bavaria münchen' },
  { label: 'Hamburg', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Frankfurt', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland finance' },
  { label: 'Cologne', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland köln' },
  { label: 'Düsseldorf', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Stuttgart', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Leipzig', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Dortmund', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Essen', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland ruhr' },
  { label: 'Bremen', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Dresden', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland saxony' },
  { label: 'Hannover', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland' },
  { label: 'Nuremberg', flag: '🇩🇪', iana: 'Europe/Berlin', search: 'germany german deutschland nürnberg bavaria' },

  // ── Netherlands, Belgium, Luxembourg ─────────────────────────────────────
  { label: 'Amsterdam', flag: '🇳🇱', iana: 'Europe/Amsterdam', search: 'netherlands holland dutch' },
  { label: 'Rotterdam', flag: '🇳🇱', iana: 'Europe/Amsterdam', search: 'netherlands holland dutch' },
  { label: 'The Hague', flag: '🇳🇱', iana: 'Europe/Amsterdam', search: 'netherlands holland dutch den haag' },
  { label: 'Utrecht', flag: '🇳🇱', iana: 'Europe/Amsterdam', search: 'netherlands holland dutch' },
  { label: 'Eindhoven', flag: '🇳🇱', iana: 'Europe/Amsterdam', search: 'netherlands holland dutch' },
  { label: 'Brussels', flag: '🇧🇪', iana: 'Europe/Brussels', search: 'belgium belgian capital' },
  { label: 'Antwerp', flag: '🇧🇪', iana: 'Europe/Brussels', search: 'belgium belgian' },
  { label: 'Ghent', flag: '🇧🇪', iana: 'Europe/Brussels', search: 'belgium belgian' },
  { label: 'Luxembourg City', flag: '🇱🇺', iana: 'Europe/Luxembourg', search: 'luxembourg capital' },

  // ── Spain & Portugal ──────────────────────────────────────────────────────
  { label: 'Madrid', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish espana capital' },
  { label: 'Barcelona', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish catalonia' },
  { label: 'Valencia', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish' },
  { label: 'Seville', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish sevilla andalusia' },
  { label: 'Zaragoza', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish' },
  { label: 'Málaga', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish andalusia costa del sol' },
  { label: 'Bilbao', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish basque' },
  { label: 'Palma', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish mallorca balearic islands' },
  { label: 'Ibiza', flag: '🇪🇸', iana: 'Europe/Madrid', search: 'spain spanish balearic islands' },
  { label: 'Lisbon', flag: '🇵🇹', iana: 'Europe/Lisbon', search: 'portugal portuguese lisboa capital' },
  { label: 'Porto', flag: '🇵🇹', iana: 'Europe/Lisbon', search: 'portugal portuguese' },
  { label: 'Faro', flag: '🇵🇹', iana: 'Europe/Lisbon', search: 'portugal portuguese algarve' },

  // ── Italy ─────────────────────────────────────────────────────────────────
  { label: 'Rome', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian roma capital' },
  { label: 'Milan', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian milano fashion' },
  { label: 'Naples', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian napoli' },
  { label: 'Turin', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian torino' },
  { label: 'Florence', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian firenze tuscany' },
  { label: 'Venice', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian venezia' },
  { label: 'Bologna', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian emilia romagna' },
  { label: 'Genoa', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian genova liguria' },
  { label: 'Palermo', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian sicily' },
  { label: 'Catania', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian sicily' },
  { label: 'Bari', flag: '🇮🇹', iana: 'Europe/Rome', search: 'italy italian puglia' },

  // ── Switzerland & Austria ─────────────────────────────────────────────────
  { label: 'Zurich', flag: '🇨🇭', iana: 'Europe/Zurich', search: 'switzerland swiss' },
  { label: 'Geneva', flag: '🇨🇭', iana: 'Europe/Zurich', search: 'switzerland swiss un' },
  { label: 'Bern', flag: '🇨🇭', iana: 'Europe/Zurich', search: 'switzerland swiss capital' },
  { label: 'Basel', flag: '🇨🇭', iana: 'Europe/Zurich', search: 'switzerland swiss' },
  { label: 'Lausanne', flag: '🇨🇭', iana: 'Europe/Zurich', search: 'switzerland swiss' },
  { label: 'Lucerne', flag: '🇨🇭', iana: 'Europe/Zurich', search: 'switzerland swiss' },
  { label: 'Vienna', flag: '🇦🇹', iana: 'Europe/Vienna', search: 'austria wien capital' },
  { label: 'Graz', flag: '🇦🇹', iana: 'Europe/Vienna', search: 'austria' },
  { label: 'Linz', flag: '🇦🇹', iana: 'Europe/Vienna', search: 'austria' },
  { label: 'Salzburg', flag: '🇦🇹', iana: 'Europe/Vienna', search: 'austria mozart' },
  { label: 'Innsbruck', flag: '🇦🇹', iana: 'Europe/Vienna', search: 'austria tyrol alps' },

  // ── Scandinavia ───────────────────────────────────────────────────────────
  { label: 'Stockholm', flag: '🇸🇪', iana: 'Europe/Stockholm', search: 'sweden swedish sverige capital' },
  { label: 'Gothenburg', flag: '🇸🇪', iana: 'Europe/Stockholm', search: 'sweden swedish göteborg' },
  { label: 'Malmö', flag: '🇸🇪', iana: 'Europe/Stockholm', search: 'sweden swedish malmo' },
  { label: 'Oslo', flag: '🇳🇴', iana: 'Europe/Oslo', search: 'norway norwegian norge capital' },
  { label: 'Bergen', flag: '🇳🇴', iana: 'Europe/Oslo', search: 'norway norwegian fjords' },
  { label: 'Trondheim', flag: '🇳🇴', iana: 'Europe/Oslo', search: 'norway norwegian' },
  { label: 'Copenhagen', flag: '🇩🇰', iana: 'Europe/Copenhagen', search: 'denmark danish kobenhavn capital' },
  { label: 'Aarhus', flag: '🇩🇰', iana: 'Europe/Copenhagen', search: 'denmark danish' },
  { label: 'Helsinki', flag: '🇫🇮', iana: 'Europe/Helsinki', search: 'finland finnish suomi capital' },
  { label: 'Tampere', flag: '🇫🇮', iana: 'Europe/Helsinki', search: 'finland finnish' },
  { label: 'Reykjavik', flag: '🇮🇸', iana: 'Atlantic/Reykjavik', search: 'iceland capital northern lights' },

  // ── Eastern Europe ────────────────────────────────────────────────────────
  { label: 'Warsaw', flag: '🇵🇱', iana: 'Europe/Warsaw', search: 'poland polish polska warszawa capital' },
  { label: 'Kraków', flag: '🇵🇱', iana: 'Europe/Warsaw', search: 'poland polish krakow' },
  { label: 'Wrocław', flag: '🇵🇱', iana: 'Europe/Warsaw', search: 'poland polish wroclaw' },
  { label: 'Gdańsk', flag: '🇵🇱', iana: 'Europe/Warsaw', search: 'poland polish gdansk' },
  { label: 'Prague', flag: '🇨🇿', iana: 'Europe/Prague', search: 'czech republic czechia praha capital' },
  { label: 'Brno', flag: '🇨🇿', iana: 'Europe/Prague', search: 'czech republic czechia' },
  { label: 'Bratislava', flag: '🇸🇰', iana: 'Europe/Bratislava', search: 'slovakia slovak capital' },
  { label: 'Budapest', flag: '🇭🇺', iana: 'Europe/Budapest', search: 'hungary hungarian capital' },
  { label: 'Bucharest', flag: '🇷🇴', iana: 'Europe/Bucharest', search: 'romania romanian bucuresti capital' },
  { label: 'Cluj-Napoca', flag: '🇷🇴', iana: 'Europe/Bucharest', search: 'romania romanian transylvania' },
  { label: 'Sofia', flag: '🇧🇬', iana: 'Europe/Sofia', search: 'bulgaria bulgarian capital' },
  { label: 'Plovdiv', flag: '🇧🇬', iana: 'Europe/Sofia', search: 'bulgaria bulgarian' },
  { label: 'Kyiv', flag: '🇺🇦', iana: 'Europe/Kyiv', search: 'ukraine ukrainian kiev capital' },
  { label: 'Kharkiv', flag: '🇺🇦', iana: 'Europe/Kyiv', search: 'ukraine ukrainian' },
  { label: 'Odessa', flag: '🇺🇦', iana: 'Europe/Kyiv', search: 'ukraine ukrainian' },
  { label: 'Lviv', flag: '🇺🇦', iana: 'Europe/Kyiv', search: 'ukraine ukrainian' },
  { label: 'Minsk', flag: '🇧🇾', iana: 'Europe/Minsk', search: 'belarus belarusian capital' },
  { label: 'Chisinau', flag: '🇲🇩', iana: 'Europe/Chisinau', search: 'moldova moldovan capital' },
  { label: 'Ljubljana', flag: '🇸🇮', iana: 'Europe/Ljubljana', search: 'slovenia slovenian capital' },
  { label: 'Zagreb', flag: '🇭🇷', iana: 'Europe/Zagreb', search: 'croatia croatian hrvatska capital' },
  { label: 'Split', flag: '🇭🇷', iana: 'Europe/Zagreb', search: 'croatia dalmatia coast' },
  { label: 'Sarajevo', flag: '🇧🇦', iana: 'Europe/Sarajevo', search: 'bosnia herzegovina capital' },
  { label: 'Belgrade', flag: '🇷🇸', iana: 'Europe/Belgrade', search: 'serbia serbian beograd capital' },
  { label: 'Novi Sad', flag: '🇷🇸', iana: 'Europe/Belgrade', search: 'serbia serbian' },
  { label: 'Podgorica', flag: '🇲🇪', iana: 'Europe/Podgorica', search: 'montenegro capital' },
  { label: 'Tirana', flag: '🇦🇱', iana: 'Europe/Tirane', search: 'albania albanian capital' },
  { label: 'Skopje', flag: '🇲🇰', iana: 'Europe/Skopje', search: 'north macedonia macedonian capital' },
  { label: 'Athens', flag: '🇬🇷', iana: 'Europe/Athens', search: 'greece greek capital' },
  { label: 'Thessaloniki', flag: '🇬🇷', iana: 'Europe/Athens', search: 'greece greek' },
  { label: 'Istanbul', flag: '🇹🇷', iana: 'Europe/Istanbul', search: 'turkey turkish turkiye' },
  { label: 'Ankara', flag: '🇹🇷', iana: 'Europe/Istanbul', search: 'turkey turkish turkiye capital' },
  { label: 'Izmir', flag: '🇹🇷', iana: 'Europe/Istanbul', search: 'turkey turkish aegean' },
  { label: 'Antalya', flag: '🇹🇷', iana: 'Europe/Istanbul', search: 'turkey turkish mediterranean' },
  { label: 'Tallinn', flag: '🇪🇪', iana: 'Europe/Tallinn', search: 'estonia estonian capital' },
  { label: 'Riga', flag: '🇱🇻', iana: 'Europe/Riga', search: 'latvia latvian capital' },
  { label: 'Vilnius', flag: '🇱🇹', iana: 'Europe/Vilnius', search: 'lithuania lithuanian capital' },
  { label: 'Nicosia', flag: '🇨🇾', iana: 'Asia/Nicosia', search: 'cyprus capital' },
  { label: 'Valletta', flag: '🇲🇹', iana: 'Europe/Malta', search: 'malta maltese capital' },
  { label: 'Monaco', flag: '🇲🇨', iana: 'Europe/Monaco', search: 'monaco principality' },

  // ── Russia ────────────────────────────────────────────────────────────────
  { label: 'Moscow', flag: '🇷🇺', iana: 'Europe/Moscow', search: 'russia russian moskva capital' },
  { label: 'St. Petersburg', flag: '🇷🇺', iana: 'Europe/Moscow', search: 'russia russian saint petersburg' },
  { label: 'Kazan', flag: '🇷🇺', iana: 'Europe/Moscow', search: 'russia russian volga' },
  { label: 'Yekaterinburg', flag: '🇷🇺', iana: 'Asia/Yekaterinburg', search: 'russia russian ural' },
  { label: 'Novosibirsk', flag: '🇷🇺', iana: 'Asia/Novosibirsk', search: 'russia russian siberia' },
  { label: 'Omsk', flag: '🇷🇺', iana: 'Asia/Omsk', search: 'russia russian siberia' },
  { label: 'Krasnoyarsk', flag: '🇷🇺', iana: 'Asia/Krasnoyarsk', search: 'russia russian siberia' },
  { label: 'Irkutsk', flag: '🇷🇺', iana: 'Asia/Irkutsk', search: 'russia russian siberia baikal' },
  { label: 'Vladivostok', flag: '🇷🇺', iana: 'Asia/Vladivostok', search: 'russia russian far east' },

  // ── Africa ────────────────────────────────────────────────────────────────
  // North Africa
  { label: 'Cairo', flag: '🇪🇬', iana: 'Africa/Cairo', search: 'egypt egyptian capital' },
  { label: 'Alexandria', flag: '🇪🇬', iana: 'Africa/Cairo', search: 'egypt egyptian' },
  { label: 'Casablanca', flag: '🇲🇦', iana: 'Africa/Casablanca', search: 'morocco moroccan' },
  { label: 'Rabat', flag: '🇲🇦', iana: 'Africa/Casablanca', search: 'morocco moroccan capital' },
  { label: 'Marrakech', flag: '🇲🇦', iana: 'Africa/Casablanca', search: 'morocco moroccan marrakesh' },
  { label: 'Fez', flag: '🇲🇦', iana: 'Africa/Casablanca', search: 'morocco moroccan fes' },
  { label: 'Tangier', flag: '🇲🇦', iana: 'Africa/Casablanca', search: 'morocco moroccan tanger' },
  { label: 'Algiers', flag: '🇩🇿', iana: 'Africa/Algiers', search: 'algeria algerian capital' },
  { label: 'Oran', flag: '🇩🇿', iana: 'Africa/Algiers', search: 'algeria algerian' },
  { label: 'Tunis', flag: '🇹🇳', iana: 'Africa/Tunis', search: 'tunisia tunisian capital' },
  { label: 'Tripoli', flag: '🇱🇾', iana: 'Africa/Tripoli', search: 'libya libyan capital' },
  // East Africa
  { label: 'Nairobi', flag: '🇰🇪', iana: 'Africa/Nairobi', search: 'kenya capital' },
  { label: 'Mombasa', flag: '🇰🇪', iana: 'Africa/Nairobi', search: 'kenya coast' },
  { label: 'Addis Ababa', flag: '🇪🇹', iana: 'Africa/Addis_Ababa', search: 'ethiopia ethiopian capital' },
  { label: 'Dar es Salaam', flag: '🇹🇿', iana: 'Africa/Dar_es_Salaam', search: 'tanzania tanzanian' },
  { label: 'Zanzibar', flag: '🇹🇿', iana: 'Africa/Dar_es_Salaam', search: 'tanzania island spice' },
  { label: 'Kampala', flag: '🇺🇬', iana: 'Africa/Kampala', search: 'uganda ugandan capital' },
  { label: 'Kigali', flag: '🇷🇼', iana: 'Africa/Kigali', search: 'rwanda capital' },
  { label: 'Bujumbura', flag: '🇧🇮', iana: 'Africa/Bujumbura', search: 'burundi capital' },
  { label: 'Djibouti City', flag: '🇩🇯', iana: 'Africa/Djibouti', search: 'djibouti capital' },
  { label: 'Mogadishu', flag: '🇸🇴', iana: 'Africa/Mogadishu', search: 'somalia somali capital' },
  { label: 'Asmara', flag: '🇪🇷', iana: 'Africa/Asmara', search: 'eritrea capital' },
  { label: 'Khartoum', flag: '🇸🇩', iana: 'Africa/Khartoum', search: 'sudan sudanese capital' },
  { label: 'Juba', flag: '🇸🇸', iana: 'Africa/Juba', search: 'south sudan capital' },
  { label: 'Antananarivo', flag: '🇲🇬', iana: 'Indian/Antananarivo', search: 'madagascar capital' },
  { label: 'Mauritius', flag: '🇲🇺', iana: 'Indian/Mauritius', search: 'mauritius island' },
  { label: 'Réunion', flag: '🇷🇪', iana: 'Indian/Reunion', search: 'reunion france island' },
  { label: 'Seychelles', flag: '🇸🇨', iana: 'Indian/Mahe', search: 'seychelles island victoria' },
  // Southern Africa
  { label: 'Cape Town', flag: '🇿🇦', iana: 'Africa/Johannesburg', search: 'south africa cpt western cape' },
  { label: 'Johannesburg', flag: '🇿🇦', iana: 'Africa/Johannesburg', search: 'south africa joburg jhb jnb' },
  { label: 'Durban', flag: '🇿🇦', iana: 'Africa/Johannesburg', search: 'south africa kwazulu natal' },
  { label: 'Pretoria', flag: '🇿🇦', iana: 'Africa/Johannesburg', search: 'south africa capital tshwane' },
  { label: 'Port Elizabeth', flag: '🇿🇦', iana: 'Africa/Johannesburg', search: 'south africa eastern cape gqeberha' },
  { label: 'Bloemfontein', flag: '🇿🇦', iana: 'Africa/Johannesburg', search: 'south africa free state capital' },
  { label: 'Windhoek', flag: '🇳🇦', iana: 'Africa/Windhoek', search: 'namibia capital' },
  { label: 'Gaborone', flag: '🇧🇼', iana: 'Africa/Gaborone', search: 'botswana capital' },
  { label: 'Harare', flag: '🇿🇼', iana: 'Africa/Harare', search: 'zimbabwe capital' },
  { label: 'Bulawayo', flag: '🇿🇼', iana: 'Africa/Harare', search: 'zimbabwe' },
  { label: 'Lusaka', flag: '🇿🇲', iana: 'Africa/Lusaka', search: 'zambia capital' },
  { label: 'Lilongwe', flag: '🇲🇼', iana: 'Africa/Blantyre', search: 'malawi capital' },
  { label: 'Maputo', flag: '🇲🇿', iana: 'Africa/Maputo', search: 'mozambique capital' },
  { label: 'Mbabane', flag: '🇸🇿', iana: 'Africa/Mbabane', search: 'eswatini swaziland capital' },
  { label: 'Maseru', flag: '🇱🇸', iana: 'Africa/Maseru', search: 'lesotho capital' },
  // West Africa
  { label: 'Lagos', flag: '🇳🇬', iana: 'Africa/Lagos', search: 'nigeria nigerian' },
  { label: 'Abuja', flag: '🇳🇬', iana: 'Africa/Lagos', search: 'nigeria nigerian capital' },
  { label: 'Kano', flag: '🇳🇬', iana: 'Africa/Lagos', search: 'nigeria nigerian north' },
  { label: 'Ibadan', flag: '🇳🇬', iana: 'Africa/Lagos', search: 'nigeria nigerian' },
  { label: 'Accra', flag: '🇬🇭', iana: 'Africa/Accra', search: 'ghana ghanaian capital' },
  { label: 'Kumasi', flag: '🇬🇭', iana: 'Africa/Accra', search: 'ghana ashanti' },
  { label: 'Dakar', flag: '🇸🇳', iana: 'Africa/Dakar', search: 'senegal senegalese capital' },
  { label: 'Abidjan', flag: '🇨🇮', iana: 'Africa/Abidjan', search: 'ivory coast cote divoire' },
  { label: 'Yamoussoukro', flag: '🇨🇮', iana: 'Africa/Abidjan', search: 'ivory coast cote divoire capital' },
  { label: 'Conakry', flag: '🇬🇳', iana: 'Africa/Conakry', search: 'guinea capital' },
  { label: 'Freetown', flag: '🇸🇱', iana: 'Africa/Freetown', search: 'sierra leone capital' },
  { label: 'Monrovia', flag: '🇱🇷', iana: 'Africa/Monrovia', search: 'liberia capital' },
  { label: 'Bamako', flag: '🇲🇱', iana: 'Africa/Bamako', search: 'mali capital' },
  { label: 'Ouagadougou', flag: '🇧🇫', iana: 'Africa/Ouagadougou', search: 'burkina faso capital' },
  { label: 'Niamey', flag: '🇳🇪', iana: 'Africa/Niamey', search: 'niger capital' },
  { label: "N'Djamena", flag: '🇹🇩', iana: 'Africa/Ndjamena', search: 'chad capital' },
  { label: 'Nouakchott', flag: '🇲🇷', iana: 'Africa/Nouakchott', search: 'mauritania capital' },
  { label: 'Banjul', flag: '🇬🇲', iana: 'Africa/Banjul', search: 'gambia capital' },
  { label: 'Bissau', flag: '🇬🇼', iana: 'Africa/Bissau', search: 'guinea-bissau capital' },
  { label: 'Praia', flag: '🇨🇻', iana: 'Atlantic/Cape_Verde', search: 'cape verde cabo verde capital' },
  // Central Africa
  { label: 'Kinshasa', flag: '🇨🇩', iana: 'Africa/Kinshasa', search: 'drc congo democratic republic capital' },
  { label: 'Lubumbashi', flag: '🇨🇩', iana: 'Africa/Lubumbashi', search: 'drc congo democratic republic' },
  { label: 'Brazzaville', flag: '🇨🇬', iana: 'Africa/Brazzaville', search: 'congo republic capital' },
  { label: 'Douala', flag: '🇨🇲', iana: 'Africa/Douala', search: 'cameroon cameroonian' },
  { label: 'Yaoundé', flag: '🇨🇲', iana: 'Africa/Douala', search: 'cameroon cameroonian capital' },
  { label: 'Libreville', flag: '🇬🇦', iana: 'Africa/Libreville', search: 'gabon capital' },
  { label: 'Malabo', flag: '🇬🇶', iana: 'Africa/Malabo', search: 'equatorial guinea capital' },
  { label: 'Luanda', flag: '🇦🇴', iana: 'Africa/Luanda', search: 'angola capital' },

  // ── Middle East ───────────────────────────────────────────────────────────
  { label: 'Dubai', flag: '🇦🇪', iana: 'Asia/Dubai', search: 'uae united arab emirates' },
  { label: 'Abu Dhabi', flag: '🇦🇪', iana: 'Asia/Dubai', search: 'uae united arab emirates capital' },
  { label: 'Sharjah', flag: '🇦🇪', iana: 'Asia/Dubai', search: 'uae united arab emirates' },
  { label: 'Riyadh', flag: '🇸🇦', iana: 'Asia/Riyadh', search: 'saudi arabia ksa capital' },
  { label: 'Jeddah', flag: '🇸🇦', iana: 'Asia/Riyadh', search: 'saudi arabia ksa' },
  { label: 'Mecca', flag: '🇸🇦', iana: 'Asia/Riyadh', search: 'saudi arabia ksa makkah holy city' },
  { label: 'Medina', flag: '🇸🇦', iana: 'Asia/Riyadh', search: 'saudi arabia ksa madinah holy city' },
  { label: 'Doha', flag: '🇶🇦', iana: 'Asia/Qatar', search: 'qatar capital' },
  { label: 'Kuwait City', flag: '🇰🇼', iana: 'Asia/Kuwait', search: 'kuwait capital' },
  { label: 'Manama', flag: '🇧🇭', iana: 'Asia/Bahrain', search: 'bahrain capital' },
  { label: 'Muscat', flag: '🇴🇲', iana: 'Asia/Muscat', search: 'oman capital' },
  { label: 'Tel Aviv', flag: '🇮🇱', iana: 'Asia/Jerusalem', search: 'israel' },
  { label: 'Jerusalem', flag: '🇮🇱', iana: 'Asia/Jerusalem', search: 'israel palestine holy city capital' },
  { label: 'Haifa', flag: '🇮🇱', iana: 'Asia/Jerusalem', search: 'israel' },
  { label: 'Amman', flag: '🇯🇴', iana: 'Asia/Amman', search: 'jordan jordanian capital' },
  { label: 'Beirut', flag: '🇱🇧', iana: 'Asia/Beirut', search: 'lebanon lebanese capital' },
  { label: 'Damascus', flag: '🇸🇾', iana: 'Asia/Damascus', search: 'syria syrian capital' },
  { label: 'Aleppo', flag: '🇸🇾', iana: 'Asia/Damascus', search: 'syria syrian' },
  { label: 'Baghdad', flag: '🇮🇶', iana: 'Asia/Baghdad', search: 'iraq iraqi capital' },
  { label: 'Basra', flag: '🇮🇶', iana: 'Asia/Baghdad', search: 'iraq iraqi' },
  { label: 'Erbil', flag: '🇮🇶', iana: 'Asia/Baghdad', search: 'iraq iraqi kurdistan' },
  { label: 'Tehran', flag: '🇮🇷', iana: 'Asia/Tehran', search: 'iran iranian persia capital' },
  { label: 'Isfahan', flag: '🇮🇷', iana: 'Asia/Tehran', search: 'iran iranian persia' },
  { label: 'Mashhad', flag: '🇮🇷', iana: 'Asia/Tehran', search: 'iran iranian persia' },
  { label: "Sana'a", flag: '🇾🇪', iana: 'Asia/Aden', search: 'yemen capital' },

  // ── South Asia ────────────────────────────────────────────────────────────
  { label: 'Mumbai', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian maharashtra bombay ist' },
  { label: 'Delhi', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian new delhi capital ist' },
  { label: 'Bangalore', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian karnataka bengaluru tech ist' },
  { label: 'Hyderabad', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian telangana ist' },
  { label: 'Chennai', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian tamil nadu madras ist' },
  { label: 'Kolkata', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian west bengal calcutta ist' },
  { label: 'Pune', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian maharashtra ist' },
  { label: 'Ahmedabad', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian gujarat ist' },
  { label: 'Jaipur', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian rajasthan pink city ist' },
  { label: 'Surat', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian gujarat ist' },
  { label: 'Lucknow', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian uttar pradesh ist' },
  { label: 'Kanpur', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian uttar pradesh ist' },
  { label: 'Nagpur', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian maharashtra ist' },
  { label: 'Goa', flag: '🇮🇳', iana: 'Asia/Kolkata', search: 'india indian beach ist' },
  { label: 'Karachi', flag: '🇵🇰', iana: 'Asia/Karachi', search: 'pakistan pakistani sindh' },
  { label: 'Lahore', flag: '🇵🇰', iana: 'Asia/Karachi', search: 'pakistan pakistani punjab' },
  { label: 'Islamabad', flag: '🇵🇰', iana: 'Asia/Karachi', search: 'pakistan pakistani capital' },
  { label: 'Faisalabad', flag: '🇵🇰', iana: 'Asia/Karachi', search: 'pakistan pakistani' },
  { label: 'Rawalpindi', flag: '🇵🇰', iana: 'Asia/Karachi', search: 'pakistan pakistani' },
  { label: 'Peshawar', flag: '🇵🇰', iana: 'Asia/Karachi', search: 'pakistan pakistani kpk' },
  { label: 'Dhaka', flag: '🇧🇩', iana: 'Asia/Dhaka', search: 'bangladesh capital' },
  { label: 'Chittagong', flag: '🇧🇩', iana: 'Asia/Dhaka', search: 'bangladesh' },
  { label: 'Colombo', flag: '🇱🇰', iana: 'Asia/Colombo', search: 'sri lanka ceylon' },
  { label: 'Kathmandu', flag: '🇳🇵', iana: 'Asia/Kathmandu', search: 'nepal capital himalayas' },
  { label: 'Thimphu', flag: '🇧🇹', iana: 'Asia/Thimphu', search: 'bhutan capital himalayas' },
  { label: 'Kabul', flag: '🇦🇫', iana: 'Asia/Kabul', search: 'afghanistan capital' },
  { label: 'Tashkent', flag: '🇺🇿', iana: 'Asia/Tashkent', search: 'uzbekistan capital silk road' },
  { label: 'Samarkand', flag: '🇺🇿', iana: 'Asia/Tashkent', search: 'uzbekistan silk road' },
  { label: 'Almaty', flag: '🇰🇿', iana: 'Asia/Almaty', search: 'kazakhstan largest city' },
  { label: 'Astana', flag: '🇰🇿', iana: 'Asia/Almaty', search: 'kazakhstan capital nur-sultan' },
  { label: 'Bishkek', flag: '🇰🇬', iana: 'Asia/Bishkek', search: 'kyrgyzstan capital' },
  { label: 'Dushanbe', flag: '🇹🇯', iana: 'Asia/Dushanbe', search: 'tajikistan capital' },
  { label: 'Ashgabat', flag: '🇹🇲', iana: 'Asia/Ashgabat', search: 'turkmenistan capital' },
  { label: 'Tbilisi', flag: '🇬🇪', iana: 'Asia/Tbilisi', search: 'georgia country capital' },
  { label: 'Yerevan', flag: '🇦🇲', iana: 'Asia/Yerevan', search: 'armenia capital' },
  { label: 'Baku', flag: '🇦🇿', iana: 'Asia/Baku', search: 'azerbaijan capital caspian' },

  // ── Southeast Asia ────────────────────────────────────────────────────────
  { label: 'Bangkok', flag: '🇹🇭', iana: 'Asia/Bangkok', search: 'thailand thai capital' },
  { label: 'Chiang Mai', flag: '🇹🇭', iana: 'Asia/Bangkok', search: 'thailand thai north' },
  { label: 'Phuket', flag: '🇹🇭', iana: 'Asia/Bangkok', search: 'thailand thai island beach' },
  { label: 'Pattaya', flag: '🇹🇭', iana: 'Asia/Bangkok', search: 'thailand thai beach' },
  { label: 'Ho Chi Minh City', flag: '🇻🇳', iana: 'Asia/Ho_Chi_Minh', search: 'vietnam vietnamese saigon south' },
  { label: 'Hanoi', flag: '🇻🇳', iana: 'Asia/Bangkok', search: 'vietnam vietnamese capital north' },
  { label: 'Da Nang', flag: '🇻🇳', iana: 'Asia/Ho_Chi_Minh', search: 'vietnam vietnamese central coast' },
  { label: 'Hoi An', flag: '🇻🇳', iana: 'Asia/Ho_Chi_Minh', search: 'vietnam vietnamese ancient town' },
  { label: 'Phnom Penh', flag: '🇰🇭', iana: 'Asia/Phnom_Penh', search: 'cambodia khmer capital' },
  { label: 'Siem Reap', flag: '🇰🇭', iana: 'Asia/Phnom_Penh', search: 'cambodia angkor wat temple' },
  { label: 'Yangon', flag: '🇲🇲', iana: 'Asia/Yangon', search: 'myanmar burma rangoon largest city' },
  { label: 'Naypyidaw', flag: '🇲🇲', iana: 'Asia/Yangon', search: 'myanmar burma capital' },
  { label: 'Vientiane', flag: '🇱🇦', iana: 'Asia/Vientiane', search: 'laos capital' },
  { label: 'Luang Prabang', flag: '🇱🇦', iana: 'Asia/Vientiane', search: 'laos temple' },
  { label: 'Singapore', flag: '🇸🇬', iana: 'Asia/Singapore', search: 'singapore city state' },
  { label: 'Kuala Lumpur', flag: '🇲🇾', iana: 'Asia/Kuala_Lumpur', search: 'malaysia malaysian kl capital' },
  { label: 'Penang', flag: '🇲🇾', iana: 'Asia/Kuala_Lumpur', search: 'malaysia food island george town' },
  { label: 'Johor Bahru', flag: '🇲🇾', iana: 'Asia/Kuala_Lumpur', search: 'malaysia singapore border' },
  { label: 'Kota Kinabalu', flag: '🇲🇾', iana: 'Asia/Kuching', search: 'malaysia sabah borneo' },
  { label: 'Kuching', flag: '🇲🇾', iana: 'Asia/Kuching', search: 'malaysia sarawak borneo' },
  { label: 'Jakarta', flag: '🇮🇩', iana: 'Asia/Jakarta', search: 'indonesia indonesian java capital' },
  { label: 'Surabaya', flag: '🇮🇩', iana: 'Asia/Jakarta', search: 'indonesia indonesian java' },
  { label: 'Bandung', flag: '🇮🇩', iana: 'Asia/Jakarta', search: 'indonesia indonesian java' },
  { label: 'Bali', flag: '🇮🇩', iana: 'Asia/Makassar', search: 'indonesia indonesian island tourist' },
  { label: 'Lombok', flag: '🇮🇩', iana: 'Asia/Makassar', search: 'indonesia indonesian island' },
  { label: 'Makassar', flag: '🇮🇩', iana: 'Asia/Makassar', search: 'indonesia indonesian sulawesi' },
  { label: 'Medan', flag: '🇮🇩', iana: 'Asia/Jakarta', search: 'indonesia indonesian sumatra' },
  { label: 'Manila', flag: '🇵🇭', iana: 'Asia/Manila', search: 'philippines filipino capital' },
  { label: 'Cebu', flag: '🇵🇭', iana: 'Asia/Manila', search: 'philippines filipino visayas' },
  { label: 'Davao', flag: '🇵🇭', iana: 'Asia/Manila', search: 'philippines filipino mindanao' },
  { label: 'Boracay', flag: '🇵🇭', iana: 'Asia/Manila', search: 'philippines filipino island beach' },
  { label: 'Brunei', flag: '🇧🇳', iana: 'Asia/Brunei', search: 'brunei darussalam' },
  { label: 'Dili', flag: '🇹🇱', iana: 'Asia/Dili', search: 'east timor timor leste capital' },

  // ── East Asia ─────────────────────────────────────────────────────────────
  { label: 'Hong Kong', flag: '🇭🇰', iana: 'Asia/Hong_Kong', search: 'hong kong hk china sar' },
  { label: 'Macau', flag: '🇲🇴', iana: 'Asia/Macau', search: 'macao china sar casino' },
  { label: 'Taipei', flag: '🇹🇼', iana: 'Asia/Taipei', search: 'taiwan roc capital' },
  { label: 'Kaohsiung', flag: '🇹🇼', iana: 'Asia/Taipei', search: 'taiwan roc south' },
  { label: 'Beijing', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese prc capital peking' },
  { label: 'Shanghai', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese prc financial hub' },
  { label: 'Guangzhou', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese canton guangdong' },
  { label: 'Shenzhen', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese tech guangdong' },
  { label: 'Chengdu', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese sichuan panda' },
  { label: 'Chongqing', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese municipality' },
  { label: 'Wuhan', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese hubei' },
  { label: 'Xi\'an', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese shaanxi silk road terracotta' },
  { label: 'Hangzhou', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese zhejiang alibaba' },
  { label: 'Nanjing', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese jiangsu' },
  { label: 'Tianjin', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese' },
  { label: 'Wuxi', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese jiangsu' },
  { label: 'Suzhou', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese jiangsu garden' },
  { label: 'Qingdao', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese shandong beer' },
  { label: 'Kunming', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese yunnan spring city' },
  { label: 'Harbin', flag: '🇨🇳', iana: 'Asia/Shanghai', search: 'china chinese heilongjiang ice festival' },
  { label: 'Seoul', flag: '🇰🇷', iana: 'Asia/Seoul', search: 'south korea korean capital' },
  { label: 'Busan', flag: '🇰🇷', iana: 'Asia/Seoul', search: 'south korea korean port' },
  { label: 'Incheon', flag: '🇰🇷', iana: 'Asia/Seoul', search: 'south korea korean airport' },
  { label: 'Daegu', flag: '🇰🇷', iana: 'Asia/Seoul', search: 'south korea korean' },
  { label: 'Jeju', flag: '🇰🇷', iana: 'Asia/Seoul', search: 'south korea korean island' },
  { label: 'Pyongyang', flag: '🇰🇵', iana: 'Asia/Pyongyang', search: 'north korea dprk capital' },
  { label: 'Tokyo', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese capital' },
  { label: 'Osaka', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese food' },
  { label: 'Kyoto', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese temple ancient' },
  { label: 'Nagoya', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese toyota' },
  { label: 'Sapporo', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese hokkaido snow' },
  { label: 'Fukuoka', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese kyushu' },
  { label: 'Hiroshima', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese' },
  { label: 'Yokohama', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese port' },
  { label: 'Kobe', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese' },
  { label: 'Naha', flag: '🇯🇵', iana: 'Asia/Tokyo', search: 'japan japanese okinawa' },
  { label: 'Ulaanbaatar', flag: '🇲🇳', iana: 'Asia/Ulaanbaatar', search: 'mongolia mongolian capital' },

  // ── Australia ─────────────────────────────────────────────────────────────
  { label: 'Sydney', flag: '🇦🇺', iana: 'Australia/Sydney', search: 'australia new south wales nsw' },
  { label: 'Melbourne', flag: '🇦🇺', iana: 'Australia/Melbourne', search: 'australia victoria vic' },
  { label: 'Brisbane', flag: '🇦🇺', iana: 'Australia/Brisbane', search: 'australia queensland qld' },
  { label: 'Gold Coast', flag: '🇦🇺', iana: 'Australia/Brisbane', search: 'australia queensland beach surfers paradise' },
  { label: 'Cairns', flag: '🇦🇺', iana: 'Australia/Brisbane', search: 'australia queensland reef' },
  { label: 'Perth', flag: '🇦🇺', iana: 'Australia/Perth', search: 'australia western wa capital' },
  { label: 'Adelaide', flag: '🇦🇺', iana: 'Australia/Adelaide', search: 'australia south sa capital' },
  { label: 'Darwin', flag: '🇦🇺', iana: 'Australia/Darwin', search: 'australia northern territory nt capital' },
  { label: 'Canberra', flag: '🇦🇺', iana: 'Australia/Sydney', search: 'australia act capital federal' },
  { label: 'Hobart', flag: '🇦🇺', iana: 'Australia/Hobart', search: 'australia tasmania capital' },
  { label: 'Newcastle AU', flag: '🇦🇺', iana: 'Australia/Sydney', search: 'australia new south wales nsw' },
  { label: 'Wollongong', flag: '🇦🇺', iana: 'Australia/Sydney', search: 'australia new south wales nsw' },

  // ── New Zealand ───────────────────────────────────────────────────────────
  { label: 'Auckland', flag: '🇳🇿', iana: 'Pacific/Auckland', search: 'new zealand nz kiwi largest' },
  { label: 'Wellington', flag: '🇳🇿', iana: 'Pacific/Auckland', search: 'new zealand nz capital' },
  { label: 'Christchurch', flag: '🇳🇿', iana: 'Pacific/Auckland', search: 'new zealand nz south island' },
  { label: 'Queenstown', flag: '🇳🇿', iana: 'Pacific/Auckland', search: 'new zealand nz adventure tourism' },

  // ── Pacific Islands ───────────────────────────────────────────────────────
  { label: 'Honolulu', flag: '🇺🇸', iana: 'Pacific/Honolulu', search: 'hawaii usa pacific aloha' },
  { label: 'Suva', flag: '🇫🇯', iana: 'Pacific/Fiji', search: 'fiji capital' },
  { label: 'Nadi', flag: '🇫🇯', iana: 'Pacific/Fiji', search: 'fiji airport resort' },
  { label: 'Papeete', flag: '🇵🇫', iana: 'Pacific/Tahiti', search: 'french polynesia tahiti france' },
  { label: 'Noumea', flag: '🇳🇨', iana: 'Pacific/Noumea', search: 'new caledonia france' },
  { label: 'Port Moresby', flag: '🇵🇬', iana: 'Pacific/Port_Moresby', search: 'papua new guinea png capital' },
  { label: 'Honiara', flag: '🇸🇧', iana: 'Pacific/Guadalcanal', search: 'solomon islands capital' },
  { label: 'Port Vila', flag: '🇻🇺', iana: 'Pacific/Efate', search: 'vanuatu capital' },
  { label: 'Apia', flag: '🇼🇸', iana: 'Pacific/Apia', search: 'samoa capital' },
  { label: "Nuku'alofa", flag: '🇹🇴', iana: 'Pacific/Tongatapu', search: 'tonga capital' },
  { label: 'Tarawa', flag: '🇰🇮', iana: 'Pacific/Tarawa', search: 'kiribati capital' },
  { label: 'Majuro', flag: '🇲🇭', iana: 'Pacific/Majuro', search: 'marshall islands capital' },
  { label: 'Palikir', flag: '🇫🇲', iana: 'Pacific/Pohnpei', search: 'micronesia capital' },
  { label: 'Koror', flag: '🇵🇼', iana: 'Pacific/Palau', search: 'palau diving' },
  { label: 'Guam', flag: '🇬🇺', iana: 'Pacific/Guam', search: 'guam usa territory pacific' },
  { label: 'Saipan', flag: '🇲🇵', iana: 'Pacific/Saipan', search: 'northern mariana islands usa' },
  { label: 'Easter Island', flag: '🇨🇱', iana: 'Pacific/Easter', search: 'chile rapa nui moai' },

  // ── Indian Ocean Islands ──────────────────────────────────────────────────
  { label: 'Malé', flag: '🇲🇻', iana: 'Indian/Maldives', search: 'maldives capital' },
  { label: 'Victoria SC', flag: '🇸🇨', iana: 'Indian/Mahe', search: 'seychelles capital' },
  { label: 'Port Louis', flag: '🇲🇺', iana: 'Indian/Mauritius', search: 'mauritius capital' },
  { label: 'Saint-Denis', flag: '🇷🇪', iana: 'Indian/Reunion', search: 'reunion france island capital' },
  { label: 'Moroni', flag: '🇰🇲', iana: 'Indian/Comoro', search: 'comoros capital' },

  // ── Atlantic Islands ──────────────────────────────────────────────────────
  { label: 'Praia', flag: '🇨🇻', iana: 'Atlantic/Cape_Verde', search: 'cape verde cabo verde capital' },
  { label: 'São Tomé', flag: '🇸🇹', iana: 'Africa/Sao_Tome', search: 'sao tome principe island' },
  { label: 'Stanley', flag: '🇫🇰', iana: 'Atlantic/Stanley', search: 'falkland islands malvinas' },
  { label: 'Longyearbyen', flag: '🇳🇴', iana: 'Arctic/Longyearbyen', search: 'svalbard norway arctic' },
]
